//This represents the MongoDatabase
module.exports = [
    {
        id: 101,
        name: 'Black and Decker 20 volt 3/8 in. Brushed Cordless Compact Drill Kit (Battery & Charger Included)',
        product_type: 'powerdrills',
        brand: 'Black and Decker',
        img: 'powerdrill1',
        price: 49.99,
        review_count: 35,
        rating: 3.5,
        hidden_by_filter: false,
        sub_type: 'cordless-drills',
        battery_type: 'Lithium Ion'
    },
    {
        id: 102,
        name: 'Craftsman 20V MAX 20 volt 1/2 in. Brushed Cordless Drill Kit (Battery & Charger Included)',
        product_type: 'powerdrills',
        brand: 'Craftsman',
        img: 'powerdrill2',
        price: 79.99,
        review_count: 64,
        rating: 4.6,
        hidden_by_filter: false,
        sub_type: 'cordless-drills',
        battery_type: 'Lithium Ion'
    },
    {
        id: 103,
        name: '20-Volt Compact Cordless Drill Kit, 3/8-In., Lithium-Ion Battery',
        product_type: 'powerdrills',
        brand: 'Master Mechanic',
        img: 'powerdrill3',
        price: 74.99,
        discount_price: 50.00,
        review_count: 20,
        rating: 3,
        hidden_by_filter: false,
        sub_type: 'cordless-drills',
        battery_type: 'Lithium Ion'
    },
    {
        id: 104,
        name: 'Kobalt XTR 24-Volt Max 1/2-in Brushless Cordless Drill (Charger Included and 1-Battery Included)',
        product_type: 'powerdrills',
        brand: 'Kobalt',
        img: 'powerdrill4',
        price: 169.00,
        review_count: 30,
        rating: 5,
        hidden_by_filter: false,
        sub_type: 'cordless-drills',
        battery_type: 'Other'
    },
    {
        id: 105,
        name: 'Rockwell ShopSeries 18 volt 3/8 in. Brushless Cordless Drill Kit (Battery & Charger Included) ',
        product_type: 'powerdrills',
        brand: 'Rockwell',
        img: 'powerdrill5',
        price: 64.99,
        review_count: 0,
        rating: 0,
        hidden_by_filter: false,
        sub_type: 'cordless-drills',
        battery_type: 'Ni-Cad'
    }, //LAWN MOWERS
    {
        id: 201,
        name: "EGO LM2102SP 21 in. 56 volt Battery Self-Propelled Lawn Mower",
        product_type: "lawnmowers",
        brand: "EGO",
        img: "lawnmower1",
        price: 569.99,
        review_count: 50,
        rating: 4.5,
        hidden_by_filter: false,
        sub_type: "pushmowers",
        powered_by: "Battery"
    },
    {
        id: 202,
        name: "Craftsman 12AVB2R3791 163 cc Gas Self-Propelled Lawn Mower",
        product_type: "lawnmowers",
        brand: "Craftsman",
        img: "lawnmower2",
        price: 339.99,
        review_count: 42,
        rating: 3,
        hidden_by_filter: false,
        sub_type: "pushmowers",
        powered_by: "Gas"
    },
    {
        id: 203,
        name: "Toro Power Reverse Personal Pace 22 in. 159 cc Gas Self-Propelled Lawn Mower Kit",
        product_type: "lawnmowers",
        brand: "Toro",
        img: "lawnmower3",
        price: 459.00,
        review_count: 4,
        rating: 4.8,
        hidden_by_filter: false,
        sub_type: "pushmowers",
        powered_by: "Gas"
    },
    {
        id: 204,
        name: "Craftsman 30 in. 382 cc Gear Gas Lawn Tractor",
        product_type: "lawnmowers",
        brand: "Craftsman",
        img: "lawnmower4",
        price: 1249.99,
        review_count: 4,
        rating: 4.8,
        hidden_by_filter: false,
        sub_type: "ridingmowers",
        powered_by: "Gas"
    }
]