//This represents the MongoDatabase
module.exports = [
    {
        id: 101,
        name: 'Black and Decker 20 volt 3/8 in. Brushed Cordless Compact Drill Kit (Battery & Charger Included)',
        product_type: 'powerdrills',
        brand: 'blackanddecker',
        brand_name: 'Black and Decker',
        img: 'powerdrill1',
        price: 49.99,
        review_count: 35,
        rating: 3.5,
        hidden_by_filter: false,
        sub_type: 'cordless-drills',
        battery_type: 'Lithium Ion'
    },
    {
        id: 102,
        name: 'Craftsman 20V MAX 20 volt 1/2 in. Brushed Cordless Drill Kit (Battery & Charger Included)',
        product_type: 'powerdrills',
        brand: 'craftsman',
        brand_name: 'Craftsman',
        img: 'powerdrill2',
        price: 79.99,
        review_count: 64,
        rating: 4.6,
        hidden_by_filter: false,
        sub_type: 'cordless-drills',
        battery_type: 'Lithium Ion'
    },
    {
        id: 103,
        name: '20-Volt Compact Cordless Drill Kit, 3/8-In., Lithium-Ion Battery',
        product_type: 'powerdrills',
        brand: 'mastermechanic',
        brand_name: 'Master Mechanic',
        img: 'powerdrill3',
        price: 74.99,
        discount_price: 50.00,
        review_count: 20,
        rating: 3,
        hidden_by_filter: false,
        sub_type: 'cordless-drills',
        battery_type: 'Lithium Ion'
    },
    {
        id: 104,
        name: 'Kobalt XTR 24-Volt Max 1/2-in Brushless Cordless Drill (Charger Included and 1-Battery Included)',
        product_type: 'powerdrills',
        brand: 'kobalt',
        brand_name: 'Kobalt',
        img: 'powerdrill4',
        price: 169.00,
        review_count: 30,
        rating: 5,
        hidden_by_filter: false,
        sub_type: 'cordless-drills',
        battery_type: 'Other'
    },
    {
        id: 105,
        name: 'Rockwell ShopSeries 18 volt 3/8 in. Brushless Cordless Drill Kit (Battery & Charger Included) ',
        product_type: 'powerdrills',
        brand: 'rockwell',
        brand_name: 'Rockwell',
        img: 'powerdrill5',
        price: 64.99,
        review_count: 0,
        rating: 0,
        hidden_by_filter: false,
        sub_type: 'cordless-drills',
        battery_type: 'Ni-Cad'
    },
    {
        id: 106,
        name: 'Black and Decker 5.2-Amp 3/8-in Keyless Corded Drill',
        product_type: 'powerdrills',
        brand: 'blackanddecker',
        brand_name: 'Black and Decker',
        img: 'powerdrill6',
        price: 34.98,
        review_count: 19,
        rating: 4.5,
        hidden_by_filter: false,
        sub_type: 'corded-drills',
    }, //LAWN MOWERS
    {
        id: 201,
        name: "EGO LM2102SP 21 in. 56 volt Battery Self-Propelled Lawn Mower",
        product_type: "lawnmowers",
        brand: "ego",
        brand_name: "EGO",
        img: "lawnmower1",
        price: 569.99,
        review_count: 50,
        rating: 4.5,
        hidden_by_filter: false,
        sub_type: "pushmowers",
        powered_by: "Battery"
    },
    {
        id: 202,
        name: "Craftsman 12AVB2R3791 163 cc Gas Self-Propelled Lawn Mower",
        product_type: "lawnmowers",
        brand: "craftsman",
        brand_name: "Craftsman",
        img: "lawnmower2",
        price: 339.99,
        review_count: 42,
        rating: 3,
        hidden_by_filter: false,
        sub_type: "pushmowers",
        powered_by: "Gas"
    },
    {
        id: 203,
        name: "Toro Power Reverse Personal Pace 22 in. 159 cc Gas Self-Propelled Lawn Mower Kit",
        product_type: "lawnmowers",
        brand: "toro",
        brand_name: "Toro",
        img: "lawnmower3",
        price: 459.00,
        review_count: 4,
        rating: 4.8,
        hidden_by_filter: false,
        sub_type: "pushmowers",
        powered_by: "Gas"
    },
    {
        id: 204,
        name: "Craftsman 30 in. 382 cc Gear Gas Lawn Tractor",
        product_type: "lawnmowers",
        brand: "craftsman",
        brand_name: "Craftsman",
        img: "lawnmower4",
        price: 1249.99,
        review_count: 4,
        rating: 4.8,
        hidden_by_filter: false,
        sub_type: "ridingmowers",
        powered_by: "Gas"
    }, //SNOW BLOWERS
    {
        id: 301,
        name: "Craftsman Quiet 26 in. 208 cc Two Stage Electric Start Gas Snow Blower",
        product_type: "snowblowers",
        brand: "craftsman",
        brand_name: "Craftsman",
        img: "snowblower1",
        price: 999.99,
        review_count: 4,
        rating: 3.4,
        hidden_by_filter: false,
        powered_by: "Gas",
        stage: "Two Stage"
    },
    {
        id: 302,
        name: "EGO Power+ 24 in. Two Stage Electric Start 56 volt Battery Snow Blower Kit (Battery & Charger) ",
        product_type: "snowblowers",
        brand: "ego",
        brand_name: "EGO",
        img: "snowblower2",
        price: 1299.99,
        review_count: 26,
        rating: 4.9,
        hidden_by_filter: false,
        powered_by: "Battery",
        stage: "Two Stage"
    },
    {
        id: 303,
        name: "EGO Power+ 21 in. Single Stage Electric Start 56 volt Battery Snow Blower Kit (Battery & Charge)",
        product_type: "snowblowers",
        brand: "ego",
        brand_name: "EGO",
        img: "snowblower3",
        price: 599.99,
        review_count: 602,
        rating: 4.2,
        hidden_by_filter: false,
        powered_by: "Battery",
        stage: "Single Stage"
    },
    {
        id: 304,
        name: "Toro 18 in. Single Stage Electric Snow Blower",
        product_type: "snowblowers",
        brand: "toro",
        brand_name: "Toro",
        img: "snowblower4",
        price: 259.99,
        review_count: 550,
        rating: 4.1,
        hidden_by_filter: false,
        powered_by: "Electric",
        stage: "Single Stage"
    },
    {
        id: 305,
        name: "Ariens Deluxe 24 in. 254 cc Two Stage Electric Start 120 volt Gas Snow Blower ",
        product_type: "snowblowers",
        brand: "ariens",
        brand_name: "Ariens",
        img: "snowblower5",
        price: 1099.99,
        review_count: 1,
        rating: 5,
        hidden_by_filter: false,
        powered_by: "Gas",
        stage: "Two Stage"
    },
    {
        id: 306,
        name: "Toro Power Max 28 in. 265 cc Two Stage Electric Start Gas Snow Blower",
        product_type: "snowblowers",
        brand: "toro",
        brand_name: "Toro",
        img: "snowblower6",
        price: 1399.00,
        review_count: 53,
        rating: 4.1,
        hidden_by_filter: false,
        powered_by: "Gas",
        stage: "Two Stage"
    }, //GRILLS
    {
        id: 401,
        name: "Kamado Joe 18 in. Classic I Charcoal Kamado Grill and Smoker Red",
        product_type: "grills",
        brand: "kamadojoe",
        brand_name: "Kamado Joe",
        img: "grill1",
        price: 999.99,
        review_count: 2,
        rating: 4.1,
        hidden_by_filter: false,
        sub_type: "charcoal-grills"
    },
    {
        id: 402,
        name: "Weber 22 in. Original Kettle Premium Charcoal Grill Black",
        product_type: "grills",
        brand: "weber",
        brand_name: "WEBER",
        img: "grill2",
        price: 165.00,
        review_count: 2890,
        rating: 4.9,
        hidden_by_filter: false,
        sub_type: "charcoal-grills"
    },
    {
        id: 403,
        name: "Weber Spirit II E-210 2 burners Liquid Propane Grill Black",
        product_type: "grills",
        brand: "weber",
        brand_name: "WEBER",
        img: "grill3",
        price: 379.00,
        review_count: 699,
        rating: 3.9,
        hidden_by_filter: false,
        sub_type: "gas-grills",
    },
    {
        id: 404,
        name: "Weber SmokeFire EX 4 2ND GEN Wood Pellet Grill Black ",
        product_type: "grills",
        brand: "weber",
        brand_name: "WEBER",
        img: "grill4",
        price: 999.00,
        review_count: 215,
        rating: 4,
        hidden_by_filter: false,
        sub_type: "pellet-grills",
    },
    {
        id: 405,
        name: "Ooni Fyra Charcoal/Wood Pellet Outdoor Pizza Oven Silver",
        product_type: "grills",
        brand: "ooni",
        brand_name: "Ooni",
        img: "grill5",
        price: 249.99,
        review_count: 12,
        rating: 3.5,
        hidden_by_filter: false,
        sub_type: "charcoal-grills"
    },
    {
        id: 406,
        name: "Oklahoma Joe's Wood Pellet Grill and Smoker Black",
        product_type: "grills",
        brand: "oklahomajoes",
        brand_name: "Oklahoma Joe's",
        img: "grill6",
        price: 599.00,
        review_count: 1,
        rating: 1,
        hidden_by_filter: false,
        sub_type: "pellet-grills",
    },
    {
        id: 407,
        name: "Broil King Baron Pellet 500 Wood Pellet Grill and Smoker Black",
        product_type: "grills",
        brand: "broilking",
        brand_name: "Broil King",
        img: "grill7",
        price: 999.00,
        review_count: 15,
        rating: 4.2,
        hidden_by_filter: false,
        sub_type: "pellet-grills",
    },
    {
        id: 408,
        name: "Blackstone 2 burners Liquid Propane Outdoor Griddle Black",
        product_type: "grills",
        brand: "blackstone",
        brand_name: "Blackstone",
        img: "grill8",
        price: 199.99,
        review_count: 1,
        rating: 4,
        hidden_by_filter: false,
        sub_type: "gas-grills",
    },
    {
        id: 409,
        name: "Ooni Koda Gas-Powered Outdoor Pizza Oven 1 burners Liquid Propane Pizza Oven Black",
        product_type: "grills",
        brand: "ooni",
        brand_name: "Ooni",
        img: "grill9",
        price: 329.99,
        review_count: 2,
        rating: 5,
        hidden_by_filter: false,
        sub_type: "gas-grills",
    }, //CHAINSAWS
    {
        id: 501,
        name: "EGO Power+ CS1604 16 in. 56 volt Battery Chainsaw Kit (Battery & Charger)",
        product_type: "chainsaws",
        brand: "ego",
        brand_name: "EGO",
        img: "chainsaw1",
        price: 299.99,
        review_count: 3400,
        rating: 4.7,
        hidden_by_filter: false,
        powered_by: "Battery",
        start_type: "Push Button"
    },
    {
        id: 502,
        name: "Craftsman 16 in. 120 volt Electric Chainsaw",
        product_type: "chainsaws",
        brand: "craftsman",
        brand_name: "Craftsman",
        img: "chainsaw2",
        price: 89.99,
        review_count: 24,
        rating: 3.7,
        hidden_by_filter: false,
        powered_by: "Electric",
        start_type: "Push Button"
    },
    {
        id: 503,
        name: "STIHL MS 250 18 in. 45.4 cc Gas Chainsaw",
        product_type: "chainsaws",
        brand: "stihl",
        brand_name: "STIHL",
        img: "chainsaw3",
        price: 349.99,
        review_count: 447,
        rating: 2.9,
        hidden_by_filter: false,
        powered_by: "Gas",
        start_type: "Pull Start"
    },
    {
        id: 504,
        name: "Craftsman S185 18 in. 42 cc Gas Chainsaw",
        product_type: "chainsaws",
        brand: "craftsman",
        brand_name: "Craftsman",
        img: "chainsaw4",
        price: 179.99,
        review_count: 24,
        rating: 4.9,
        hidden_by_filter: false,
        powered_by: "Gas",
        start_type: "Pull Start"
    },
    {
        id: 505,
        name: "STIHL MSA 140 C-BQ 12 in. Battery Chainsaw",
        product_type: "chainsaws",
        brand: "stihl",
        brand_name: "STIHL",
        img: "chainsaw5",
        price: 349.95,
        review_count: 54,
        rating: 3.9,
        hidden_by_filter: false,
        powered_by: "Battery",
        start_type: "Push Button"
    }
]